/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaopt_MatrixMultiplication */

#ifndef _Included_javaopt_MatrixMultiplication
#define _Included_javaopt_MatrixMultiplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaopt_MatrixMultiplication
 * Method:    nativeVariant
 * Signature: ([I[I[IIII)V
 */
JNIEXPORT void JNICALL Java_javaopt_MatrixMultiplication_nativeVariant
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
