/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaopt_NativeMethods */

#ifndef _Included_javaopt_NativeMethods
#define _Included_javaopt_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaopt_NativeMethods
 * Method:    dieStackOverflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_dieStackOverflow
  (JNIEnv *, jobject);

/*
 * Class:     javaopt_NativeMethods
 * Method:    mallocNBytes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_mallocNBytes
  (JNIEnv *, jobject, jint);

/*
 * Class:     javaopt_NativeMethods
 * Method:    dieFirstMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_dieFirstMethod
  (JNIEnv *, jobject);

/*
 * Class:     javaopt_NativeMethods
 * Method:    dieNestedMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_dieNestedMethod
  (JNIEnv *, jobject);

/*
 * Class:     javaopt_NativeMethods
 * Method:    showStackTrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_showStackTrace
  (JNIEnv *, jobject);

/*
 * Class:     javaopt_NativeMethods
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javaopt_NativeMethods_strlen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     javaopt_NativeMethods
 * Method:    printBeanNum
 * Signature: (Ljavaopt/Bean;)V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_printBeanNum
  (JNIEnv *, jobject, jobject);

/*
 * Class:     javaopt_NativeMethods
 * Method:    changeBeanNum
 * Signature: (Ljavaopt/Bean;I)V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_changeBeanNum
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     javaopt_NativeMethods
 * Method:    secretStructInit
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_javaopt_NativeMethods_secretStructInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     javaopt_NativeMethods
 * Method:    secretStructValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javaopt_NativeMethods_secretStructValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javaopt_NativeMethods
 * Method:    secretStructFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javaopt_NativeMethods_secretStructFree
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
